#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-irclib
Version  : 1.10
Release  : 1
URL      : https://master.dl.sourceforge.net/project/moepii/IRClib%20%28IRC%20client%20library%29/1.10/irclib-1.10.tar.gz
Source0  : https://master.dl.sourceforge.net/project/moepii/IRClib%20%28IRC%20client%20library%29/1.10/irclib-1.10.tar.gz
Source1  : https://repo1.maven.org/maven2/org/schwering/irclib/1.10/irclib-1.10.jar
Source2  : https://repo1.maven.org/maven2/org/schwering/irclib/1.10/irclib-1.10.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0 LGPL-2.1
Requires: mvn-irclib-data = %{version}-%{release}
Requires: mvn-irclib-license = %{version}-%{release}

%description
IRClib is client library for Internet Relay Chat (IRC) licensed under the
* GNU Lesser General Public License (see COPYING_LGPL),
* Apache License, Version 2.0 (see COPYING_AL) and
* Eclipse Public License (see COPYING_EPL).

%package data
Summary: data components for the mvn-irclib package.
Group: Data

%description data
data components for the mvn-irclib package.


%package license
Summary: license components for the mvn-irclib package.
Group: Default

%description license
license components for the mvn-irclib package.


%prep
%setup -q -n irclib-1.10

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-irclib
cp COPYING_AL %{buildroot}/usr/share/package-licenses/mvn-irclib/COPYING_AL
cp COPYING_EPL %{buildroot}/usr/share/package-licenses/mvn-irclib/COPYING_EPL
cp COPYING_LGPL %{buildroot}/usr/share/package-licenses/mvn-irclib/COPYING_LGPL
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/schwering/irclib/1.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/schwering/irclib/1.10/irclib-1.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/schwering/irclib/1.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/schwering/irclib/1.10/irclib-1.10.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/schwering/irclib/1.10/irclib-1.10.jar
/usr/share/java/.m2/repository/org/schwering/irclib/1.10/irclib-1.10.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-irclib/COPYING_AL
/usr/share/package-licenses/mvn-irclib/COPYING_EPL
/usr/share/package-licenses/mvn-irclib/COPYING_LGPL
